'''
5+2结构
一共七个结构，五个主体，两个中间件
五个主体：SPIDERS,ENGINE,DOWNLOADER,ITEM PIPELINES,SCHEDULER
两个中间件:SPIDERS和ENGINES中间，ENGINE和DOWNLOADER中间
三条主要数据流:
    1.  SPIDERS (REQUESTS) -> ENGINE -> SCHEDULER
    2.  SCHEDULER (REQUESTS) -> ENGINE (REQUESTS) -> DOWNLOADER (RESPONSE) -> ENGINE (RESPONSE) -> SPIDERS
    3.  SPIDERS (ITEMS/REQUESTS) -> ENGINE (ITEMS)    -> ITEM PIPELINES
                                           (REQUESTS) -> SCHEDULER
'''