'''
路径操作
os.path.abspath(path)
返回path在当前系统中的绝对路径
os.path.normpath(path)
归一化path的表示形式，统一用\\分隔路径
os.path.relpath(path)
返回当前程序与文件之间的相对路径(relative path)
os.path.dirname(path)
返回path中的目录名称
os.path.basename(path)
返回path中最后的文件名称
os.path.join(path,*paths)
组合path与paths,返回一个路径字符串
os.path.exists(path)
判断path对应的文件或目录是否存在，返回True或False
os.path.isfile(path)
os.path.isdir(path)
判断path对应的是否为文件或目录，若不存在也返回False
os.path.getatime(path)(access)
返回path对应文件或目录上一次的访问时间
os.path.getmtime(path)(modify)
返回path对应文件或目录最近一次修改的时间
os.path.getctime(path)(create)
返回path对应文件或目录的创建时间
os.path.getsize(path)
返回路径对应的文件或目录的大小

进程管理
os.system(command)
command用字符串来写就好了

环境参数
os.chdir(path)
修改当前程序操作的路径
os.getcwd()
返回程序的当前路径
os.getlogin()
获得系统登录用户名称
os.cpu_count()
获得当前系统的cpu数量
os.urandom(n)
获得一个n个字节长度的随机字符串，通常用于加解密运算
'''
